### ISSUE TITLE
Would forest0.world file be open?

### ISSUE THREAD

**Issue by KahnShi** [vsu91/ewok#2]
Hi @vsu91 

I read your paper and played with your simulator, it is excellent!
Thank you for your work to make it open source.

Then when I try to launch trajectory_replanning_forest.launch, I found forest0.world file is missing.
Would it be open in the future?

Thx in advance.

**Comment by vsu91** [comment]
Hi @KahnShi,

I've received the forest dataset from the authors of the following paper:
Helen Oleynikova, Michael Burri, Zachary Taylor, Juan Nieto, Roland Siegwart, and Enric Galceran, “Continuous-Time Trajectory Optimization for Online UAV Replanning”. In IEEE Int. Conf. on Intelligent Robots and Systems (IROS), October 2016.

I cannot redistribute it further, but you can probably contact the authors to get access to it. You can find the paper and emails of the authors here:
http://helenol.github.io/

Cheers,
Vlad

**Comment by KahnShi** [comment]
Thank you for your advice Vlad! @vsu91 
I will try to contact her.

Best,
Kahn
